### ISSUE TITLE
Deploy Metabase to ECS

### ISSUE THREAD

**Issue by pcr0wley** [crowleysystems/metabase#1]
This issue is to deploy Metabase to ECS. Currently it is running in Docker on EC2.

### `docker-compose.yml`
```
version: '3'

services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    user: metabase
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: PASSWORD
      MB_DB_HOST: HOST
      MB_PLUGINS_DIR: ./plugins
```

### `Dockerfile`
```
# Stage 1: Build stage
FROM metabase/metabase:latest AS build
WORKDIR /temp
# Copy necessary files from metabase image
COPY --from=metabase/metabase:latest /app /temp

# Stage 2: Final stage
FROM eclipse-temurin:11
WORKDIR /app
# Copy files from build stage
COPY --from=build /temp /app
RUN useradd -ms /bin/sh metabase && chown -R metabase /app

# Copy custom addons
COPY --chown=metabase ./plugins /app/plugins
#COPY ./plugins /app/plugins
#COPY ./clickhouse.metabase-driver.jar /app/plugins/clickhouse.metabase-driver.jar
#RUN chmod 744 /app/plugins/clickhouse.metabase-driver.jar

USER metabase

ENTRYPOINT ["/app/run_metabase.sh"]
```

### `/plugins`
Contains `clickhouse.metabase-driver.jar`.
